<?php

//$GLOBALS['header_path'] = dirname(__DIR__)."/FurnitureStore/View/header.php";
//$GLOBALS['product_path']= dirname(__DIR__)."/FurnitureStore/Model/product.php";
//$GLOBALS['order_path']= dirname(__DIR__)."/FurnitureStore/Model/order.php";
//$GLOBALS['delivery_path']= dirname(__DIR__)."/FurnitureStore/Model/delivery.php";
//$GLOBALS['customer_path']= dirname(__DIR__)."/FurnitureStore/Model/customer.php";
//$GLOBALS['billing_path']= dirname(__DIR__)."/FurnitureStore/Model/billing.php";
//$GLOBALS['showProducts_path']= dirname(__DIR__)."/FurnitureStore/Controller/showProducts.php";
//$GLOBALS['showOrder_path']= dirname(__DIR__)."/FurnitureStore/Controller/showOrder.php";
//$GLOBALS['placeOrder_path']= dirname(__DIR__)."/FurnitureStore/Controller/placeOrder.php";
//$GLOBALS['payment_path']= dirname(__DIR__)."/FurnitureStore/Controller/payment.php";
//$GLOBALS['checkout_path']= dirname(__DIR__)."/FurnitureStore/Controller/checkout.php";
//$GLOBALS['cart_path']= dirname(__DIR__)."/FurnitureStore/Controller/cart/cart.php";
//$GLOBALS['cart_update_path']= dirname(__DIR__)."/FurnitureStore/Controller/cart/cart_update.php";
//$GLOBALS['showCart_path']= dirname(__DIR__)."/FurnitureStore/Controller/cart/showCart.php";
//$GLOBALS['login_path']= dirname(__DIR__)."/FurnitureStore/Controller/user/login.php";
//$GLOBALS['logout_path']= dirname(__DIR__)."/FurnitureStore/Controller/user/logout.php";
//$GLOBALS['login_validate_path']= dirname(__DIR__)."/FurnitureStore/Controller/user/login_validate.php";
//$GLOBALS['connect_path']= dirname(__DIR__)."/FurnitureStore/config/connect.php";

$GLOBALS['header_path'] = "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/View/header.php";
$GLOBALS['product_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Model/product.php";
$GLOBALS['order_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Model/order.php";
$GLOBALS['delivery_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Model/delivery.php";
$GLOBALS['customer_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Model/customer.php";
$GLOBALS['billing_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Model/billing.php";
$GLOBALS['showProducts_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Controller/showProducts.php";
$GLOBALS['showOrder_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Controller/showOrder.php";
$GLOBALS['placeOrder_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Controller/placeOrder.php";
$GLOBALS['payment_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Controller/payment.php";
$GLOBALS['checkout_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Controller/checkout.php";
$GLOBALS['cart_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Controller/cart/cart.php";
$GLOBALS['cart_update_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Controller/cart/cart_update.php";
$GLOBALS['showCart_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Controller/cart/showCart.php";
$GLOBALS['login_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Controller/user/login.php";
$GLOBALS['logout_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Controller/user/logout.php";
$GLOBALS['login_validate_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/Controller/user/login_validate.php";
$GLOBALS['connect_path']= "/home3/wanshuwe/public_html/SYST10199"."/FurnitureStore/config/connect.php";
